# Generated by Django 4.0.4 on 2022-05-05 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viloyatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bemorlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ism', models.CharField(max_length=20)),
                ('Familiya', models.CharField(max_length=20)),
                ('Otasini_ismi', models.CharField(max_length=20)),
                ('Shahar_yoki_tuman', models.CharField(max_length=20)),
                ('Mahallas', models.CharField(max_length=20)),
                ('Kocha', models.CharField(max_length=20)),
                ('Uy_raqam', models.IntegerField()),
                ('Tugilgan_sana', models.DateField(auto_now=True)),
                ('Bolim_nomi', models.CharField(max_length=20)),
                ('Kimning_qabulida', models.CharField(max_length=20)),
                ('Telefon', models.IntegerField()),
                ('Qoshimch_malumot', models.CharField(max_length=30)),
                ('Kelgan_sanasi', models.DateField(auto_now=True)),
                ('Viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpfiles.viloyatlar')),
            ],
        ),
    ]
