# Generated by Django 4.0.4 on 2022-05-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bemorlar',
            name='Tugilgan_sana',
            field=models.DateField(default=''),
        ),
    ]
