# Generated by Django 4.0.4 on 2022-05-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpfiles', '0002_alter_bemorlar_tugilgan_sana'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bemorlar',
            new_name='Bemorlar_baza',
        ),
    ]
